"""empty message

Revision ID: 3ae7530ca1af
Revises: a8be1a4aee7a
Create Date: 2016-02-29 23:45:55.302469

"""

# revision identifiers, used by Alembic.
revision = '3ae7530ca1af'
down_revision = 'a8be1a4aee7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'myprofile_image_key', 'myprofile', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'myprofile_image_key', 'myprofile', [u'image'])
    ### end Alembic commands ###
