"""empty message

Revision ID: 76b0bf48e27a
Revises: 3ae7530ca1af
Create Date: 2016-02-29 23:58:13.341400

"""

# revision identifiers, used by Alembic.
revision = '76b0bf48e27a'
down_revision = '3ae7530ca1af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('age', sa.String(length=2), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('myprofile')
    ### end Alembic commands ###
